### ISSUE TITLE
The report "Show criterion text" button does not work using either mouse or keyboard

### ISSUE THREAD

**Issue by accessiblewebuk** [w3c/wcag-em-report-tool#290]
Checked on Mac in both Chrome and Firefox - this is with the report html and css files both loaded.

**Comment by tinynow** [comment]
It looks like a function is being called that does not exist `toggleCriterionText(this)`

**Comment by scottsb** [comment]
The function actually does exist: it just is missing the name `toggleCriterionText`.

But it looks like this was already fixed in fc58908 back in 2017. The version hosted on w3.org is just really old.

**Comment by rvantonisse** [comment]
Confirmed.
Opening "View report"
Download the evaluation report (HTML)
See the downloaded html report in browser
Criterion texts do not expand.

Looks like in file `controllers/viewReport.js` the replace() in the template does not match;
`replace('function (a)', ...)` => `replace('function(a)', ...)` (notice the removed space)

Using an actual regexp instead of exact string match should be more accurate here.

Will fix

**Comment by ronstauffer** [comment]
My apologies if this is fixed and I'm doing something wrong: using the hosted version on W3 (last updated Jan 17, 2020), this is still broken. Clicking "show criterion text" doesn't do anything.
<img width="420" alt="show criterion" src="https://user-images.githubusercontent.com/1081418/76021518-a90c5900-5ee2-11ea-8a87-3376d793fedf.png">

**Comment by rvantonisse** [comment]
Hey @ronstauffer , 

If this problem lives in the HTML export, then this issue is not yet fixed. I tried to solve it with #302, but there were some merge issues i did not anticipate on with the update. 

If you still experience this problem on any other page,
could you then reply with:
- Browser + version
- Url of the page where this issue lives

Thank you

**Comment by fbosma** [comment]
Hello @rvantonisse, I currently still experience this issue with the HTML export. On https://wcag-reports.elkander.nl/aalten/samen-aalten-wcag-em-toegankelijkheidsrapport09112020.html, nothing happens when clicking on the 'Show criterion text' icon.

**Comment by ronstauffer** [comment]
I confirmed that this is still an issue, as of today. Version 2.0.0, 2020-1-17 which is hosted at https://www.w3.org/WAI/eval/report-tool/#!/ has the issue. It works as long as you're running your own report, and if you save the JSON and upload it later as you're making changes, it's not a problem. But when you're finished with the report, and you export the HTML and CSS files then run them locally or post them elsewhere online, the "show criterion text" link doesn't work at all.

Videos: [link working while creating report](https://share.liederdigital.com/GGu6Kd2j) and [link not working on finished/exported report](https://share.liederdigital.com/jkueX84x).

**Comment by j354374** [comment]
I am getting this error today as well. Uncaught ReferenceError: toggleCriterionText is not defined.

I added <script src="../js/26ab0107.vendor.js"></script>
 <script src="../js/3ca62f3d.scripts.js"></script>

<script src="../js/cb6f07e.templates.js"></script>
 to my evaluation-report.html file.

Should I try a newer version that on w3.org?

**Comment by hidde** [comment]
We recently launched the [3.0.0 version of the WCAG-EM Report Tool](https://w3.org/WAI/eval/report-tool), in which this issue is fixed.

**Comment by ronstauffer** [comment]
Great, thank you!
